config/routes.rb
D3station::Application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  resources :helpers, only: [:index, :show] do
    get :twitch, on: :member
  end

  root :to => 'dashboard#show'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is_mod
      can :manage, :all
    else
      can :manage, User, id: user.id
    end
  end
end

app/models/twitch_data.rb
# inspired by https://github.com/kustom666/cathodic

require 'json'
require 'open-uri'
require 'openssl'

class TwitchData
  BASE_API = "https://api.twitch.tv/kraken"
  API_VERSION = "v2"

  METHODS = %w(preview viewers game)

  attr_accessor :online, :stream, :username

  def initialize username
    @username = username.split('/').last.split('?').first.gsub(/\u200e/, '')

    response = JSON.parse(request("streams"))
    
    @stream = response["stream"]
    @online = @stream.present?
  end

  def chat_url
    "http://twitch.tv/chat/embed?channel=#{@username}"
  end

  def video_url
    "http://www.twitch.tv/widgets/live_embed_player.swf?channel=#{@username}"
  end

  def status
    @stream["channel"]["status"]
  end

  def method_missing(method, *args, &block)
    if (!@stream.nil? && @stream.include?(method.to_s)) || METHODS.include?(method.to_s)
      @stream.try("[]", method.to_s)
    else
      super
    end
  end

  private

    def request path
      open(BASE_API + "/" + path + "/" + @username, {"Accept" => "application/vnd.twitchtv.#{API_VERSION}+json"}).read
    end
end

app/models/user.rb
# t.string :email,              :null => false, :default => ""
# t.string :encrypted_password, :null => false, :default => ""
# t.string   :reset_password_token
# t.datetime :reset_password_sent_at
# t.datetime :remember_created_at
# t.integer  :sign_in_count, :default => 0
# t.datetime :current_sign_in_at
# t.datetime :last_sign_in_at
# t.string   :current_sign_in_ip
# t.string   :last_sign_in_ip

# t.boolean    :is_mod, default: false
# t.string     :battlenet_username
# t.string     :battlenet_tag
# t.string     :twitch_username

# t.timestamps

class User < ActiveRecord::Base
  BATTLE_ID_FORMAT = /\A([^#|\s]+)#(\d+)\z/

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :twitch_username, :battlenet_id, :category_list

  validates :battlenet_id, presence: true, format: {with: BATTLE_ID_FORMAT, allow_nil: true}
  validates :battlenet_tag, uniqueness: {allow_nil: true, scope: [:battlenet_username]}

  acts_as_taggable
  acts_as_taggable_on :categories

  def twitch_data
    return nil unless twitch_username.present?
    @twitch_data ||= TwitchData.new(twitch_username)
  end

  def battlenet_id
    if battlenet_username.present? && battlenet_tag.present?
      [battlenet_username, battlenet_tag].join('#')
    else
      nil
    end
  end

  def battlenet_id= value
    if value =~ BATTLE_ID_FORMAT
      self.battlenet_username = $1
      self.battlenet_tag = $2
    end
  end

  def self.category_list
    ActsAsTaggableOn::Tag.joins(:taggings).where("taggings.context = 'categories'").pluck("tags.name")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout proc{ |c| c.request.xhr? ? false : "application" }
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
  def index
    @users = User.all
  end

  def twitch
    @user = User.find(params[:id])
    @twitch_data = @user.twitch_data
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    if resource_params[:password].blank?
      resource_params.delete("password")
      resource_params.delete("password_confirmation")
    end

    if resource.update_attributes(resource_params)
      if is_navigational_format?
        if resource.respond_to?(:pending_reconfirmation?) && resource.pending_reconfirmation?
          flash_key = :update_needs_confirmation
        end
        set_flash_message :notice, flash_key || :updated
      end
      sign_in resource_name, resource, :bypass => true
      respond_with resource, :location => after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_to *args, &block
    options = args[block_given? ? 0 : 1] || {}
    content = link_to(*args, &block)
    li_class = current_page?(options) ? "active" : ""
    content_tag :li, content, class: li_class
  end

  def battlenet_link_to user
    link_to user.battlenet_id, "http://www.battle.net/d3/en/profile/#{user.battlenet_id.parameterize}/", target: :blank
  end

  def twitch_popup_link_to user
    link_to user.twitch_username, twitch_helper_path(user), data: {toggle: "modal", target: '#twitch_modal'}
  end

  def category_list_for user
    user.category_list.map do |category|
      category
    end.join(", ")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/views/dashboard/show.html.erb
Hello World!

app/views/helpers/index.html.erb
<h2>
  Helpers
</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Categories</th>
      <th>TwitchTV</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= battlenet_link_to user %>
        </td>
        <td>
          <%= category_list_for user %>
        </td>
        <td>
          <%= twitch_popup_link_to user %>
        </td>
        <td>
          <%= link_to "Details", helper_path(user), class: "btn btn-mini" %>
        </td>
      </tr>
    <% end -%>
  </tbody>
</table>

app/views/helpers/twitch.html.erb
<% if @twitch_data.online %>
  <h2><%= @twitch_data.status %></h2>
  <object type="application/x-shockwave-flash" height="400" width="620" id="live_embed_player_flash" data="<%= @twitch_data.video_url %>" bgcolor="#000000">
    <param name="allowFullScreen" value="true" />
    <param name="allowScriptAccess" value="always" />
    <param name="allowNetworking" value="all" />
    <param name="movie" value="http://www.twitch.tv/widgets/live_embed_player.swf" />
    <param name="flashvars" value="hostname=www.twitch.tv&channel=<%= @twitch_data.username %>&auto_play=true&start_volume=25" />
  </object>

  <iframe frameborder="0" scrolling="no" id="chat_embed" src="<%= @twitch_data.chat_url %>" height="400" width="300">
  </iframe>
<% else %>
  <h1 class="text-center">OFFLINE</h1>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D3 Philanthropy Station</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name.parameterize %>-controller <%= action_name.parameterize %>-action<%= " signed-in" if user_signed_in? %>">

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "D3 Philanthropy Station", :root, class: "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <%= nav_link_to "Home", :root %>
          <%= nav_link_to "Helpers", helpers_path %>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <%= nav_link_to "Account", edit_user_registration_path %>
            <%= nav_link_to "Logout", destroy_user_session_path, method: :delete, class: "btn-danger" %>
          <% else %>
            <%= nav_link_to "Sign In", new_user_session_path %>
            <%= nav_link_to "Sign Up", new_user_registration_path %>
          <% end -%>
        </ul>
      </div>
    </div>
  </div>
</div>
<header>
  <div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.present? %>
      <div class="alert alert-<%= name %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= sanitize(msg.html_safe, tags: %w(br)) %>
      </div>
    <% end -%>
  <% end %>
  </div>
</header>

<div class="container">
  <%= yield %>
</div>

<div id="twitch_modal" class="twitch-modal modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-body"></div>
</div>
</body>
</html>